language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
services:
  - rabbitmq 
env:
  - RABBITMQ_HOST=localhost
  - RABBITMQ_PORT=61613
script:
  - python setup.py test --test=ss_test
  - python setup.py test --test=transport_test
  - python setup.py test --test=utils_test
  - python setup.py test --test=rabbitmq_test
