language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
services:
  - rabbitmq 
env:
  - RABBITMQ_HOST=localhost RABBITMQ_PORT=61613
before_install:
  - rabbitmq-plugins enable rabbitmq_stomp
install:
  - pip install virtualenv-api
script:
  - make travistests
