sudo: required

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

services:
  - docker

env:
  - RABBITMQ_HOST=localhost STOMPSERVER_HOST=localhost STD_HOST=localhost STD_VHOST=/ TRAVIS=true

addons:
  hosts:
    - my.example.com
    - my.example.org
    - my.example.net

before_install:
  - pip install poetry
  - make docker-image
  - make run-docker
  - docker inspect stomppy
  - docker logs stomppy

script:
  - make test
