sudo: required

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

services:
  - docker

env:
  - RABBITMQ_HOST=127.0.0.1 STOMPSERVER_HOST=127.0.0.1 STD_HOST=127.0.0.1 STD_VHOST=/

before_install:
  - docker build -t carlad/sinatra docker/
  - docker run -d -p 127.0.0.1:61613:62613 -p 127.0.0.1:62614:62614 -p 127.0.0.1:63613:63613 -p 127.0.0.1:64613:64613 carlad/sinatra

script:
  - make travistests
