sudo: required

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

services:
  - docker

env:
  - RABBITMQ_HOST=localhost STOMPSERVER_HOST=localhost STD_HOST=localhost STD_VHOST=/

before_install:
  - docker build -t carlad/sinatra docker/
  - docker run -d -p 61613:61613 -p 62613:62613 -p 62614:62614 -p 63613:63613 -p 64613:64613 carlad/sinatra

script:
  - make travistests
